# Generated by Django 5.1.3 on 2024-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accoomodationName', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('images', models.ImageField(upload_to='Images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Email')),
                ('cellPhone', models.IntegerField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('enrolled_university', models.CharField(choices=[('vut', 'Vaal University Of Technology'), ('nwu', 'Northwest University(Vaal Campus)'), ('other', 'Others')], max_length=2000)),
            ],
        ),
    ]
