# Generated by Django 5.1.3 on 2024-11-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='uuid',
        ),
    ]
