# Generated by Django 5.1.3 on 2024-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_company_email_landlord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bursary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_university',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
