# Generated by Django 5.1.3 on 2024-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_accommodation_images_accommodationimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
