# Generated by Django 5.1.4 on 2024-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_student_views_accommodation_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='accommodated_universities',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='offered_amenities',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='email',
            field=models.EmailField(default='maphilegman@gmail.com', max_length=254),
        ),
    ]
