# Generated by Django 5.1.3 on 2024-11-17 06:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_id_students_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomodations',
            name='id',
        ),
        migrations.AddField(
            model_name='accomodations',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
