# Generated by Django 4.2.15 on 2024-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_accomodations_id_accomodations_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='cellPhone',
            field=models.IntegerField(),
        ),
    ]
