# Generated by Django 4.2.15 on 2024-11-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_students_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bursary',
            field=models.CharField(choices=[('nsfas', 'Nsfas'), ('external_bursary', 'External Bursary'), ('other', 'Others')], max_length=2000, null=True),
        ),
    ]
