# Generated by Django 5.1.3 on 2024-11-18 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_students_bursary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accommodation_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='landlord_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('offered_amenities', models.TextField()),
                ('accommodated_universities', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landlord_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cell_phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('enrolled_university', models.CharField(choices=[('vut', 'Vaal University Of Technology'), ('nwu', 'Northwest University (Vaal Campus)'), ('other', 'Others')], max_length=50)),
                ('bursary', models.CharField(blank=True, choices=[('nsfas', 'Nsfas'), ('external_bursary', 'External Bursary'), ('other', 'Others')], max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Accomodations',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AddField(
            model_name='application',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.landlord'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
