# Generated by Django 5.1.3 on 2024-12-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_application_landlord_student_delete_accomodations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='company_email',
            new_name='email',
        ),
    ]
