# Generated by Django 5.1.3 on 2024-12-07 00:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_landlordimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accommodation_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='landlord_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('offered_amenities', models.TextField()),
                ('accommodated_universities', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landlord_logos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='landlord',
        ),
        migrations.AddField(
            model_name='application',
            name='accommodation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.accommodation'),
        ),
        migrations.AlterField(
            model_name='landlordimage',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_images', to='home.accommodation'),
        ),
        migrations.DeleteModel(
            name='Landlord',
        ),
    ]
