# Generated by Django 5.1.3 on 2024-12-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_student_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='views',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
